---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/concluir-expediente-ws-mock
    fabric8.io/scm-tag: HEAD
  labels:
    app: concluir-expediente-ws-mock
    provider: fabric8
    version: 0.0.1-SNAPSHOT
    group: com.example
  name: concluir-expediente-ws-mock
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    app: concluir-expediente-ws-mock
    provider: fabric8
    group: com.example
  strategy:
    rollingParams:
      timeoutSeconds: 3600
    type: Rolling
  template:
    metadata:
      annotations:
        fabric8.io/scm-tag: HEAD
        fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/concluir-expediente-ws-mock
      labels:
        app: concluir-expediente-ws-mock
        provider: fabric8
        version: 0.0.1-SNAPSHOT
        group: com.example
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: concluir-expediente-ws-mock:latest
        imagePullPolicy: IfNotPresent
        name: spring-boot
        ports:
        - containerPort: 8082
          name: us-cli
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        securityContext:
          privileged: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - spring-boot
      from:
        kind: ImageStreamTag
        name: concluir-expediente-ws-mock:latest
    type: ImageChange
